spring:
  data:
    solr:
      host: http://localhost:8080/solr/collection1
  activemq:
    broker-url: tcp://localhost:61616
  datasource:
    username: root
    password: 123
    url: jdbc:mysql:///nrs?characterEncoding=utf-8&serverTimezone=GMT%2B8&amp&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
